# Generated by Django 5.1.1 on 2024-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0002_newssource_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
