# Generated by Django 5.1.1 on 2025-06-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0002_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='urlToImage',
            new_name='image_url',
        ),
    ]
