# Generated by Django 5.1.1 on 2024-10-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0003_category_answer_question_comment_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='image',
        ),
    ]
