# Generated by Django 5.1.1 on 2025-06-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0003_rename_urltoimage_newsarticle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='aipc_diagnosis.newssource'),
        ),
    ]
