# Generated by Django 5.1.1 on 2025-06-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0004_alter_newsarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
