# Generated by Django 5.1.1 on 2025-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipc_diagnosis', '0005_alter_newsarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(default='No title', max_length=500),
        ),
    ]
